// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250524124906_AddingProductsCategoriesTables")]
    partial class AddingProductsCategoriesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12df2d0c-f849-4aae-99dc-393f4b4443dd"),
                            Cat_Name = "Mobile",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("ed419975-8b09-4553-bb59-43b3ed382adb"),
                            Cat_Name = "Laptop",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2a51063a-0d41-4784-97fc-0facbc3675b7"),
                            Cat_Name = "Men's Shirts",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("99798cf8-a700-4254-b641-960a278ba9e1"),
                            Cat_Name = "Men's Pents",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("d026bf3d-5e98-46fd-986e-82c97da687bf"),
                            Cat_Name = "Men's Shoes",
                            Status = true
                        });
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product_Image_Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("qty_in_stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aacee317-8fff-4a95-8047-c2b5d97c1cb6"),
                            CategoryId = new Guid("12df2d0c-f849-4aae-99dc-393f4b4443dd"),
                            Description = "iPhone 16. Built for Apple Intelligence.Featuring Camera Control. 48 MP Fusion camera.Five vibrant colours.And A18 chip.",
                            Price = 69999.00m,
                            Product_Image_Url = "/Images/iphone-16.jpg",
                            Product_Name = "Apple IPhone 16",
                            qty_in_stock = 10
                        },
                        new
                        {
                            Id = new Guid("6fda0a9a-fa97-4f5a-9d70-5dca4a75414e"),
                            CategoryId = new Guid("12df2d0c-f849-4aae-99dc-393f4b4443dd"),
                            Description = "iPhone 13.boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity.Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension",
                            Price = 44999.00m,
                            Product_Image_Url = "/Images/iphone-13.jpg",
                            Product_Name = "Apple IPhone 13",
                            qty_in_stock = 10
                        },
                        new
                        {
                            Id = new Guid("6117ca3d-1ff8-4ddf-a414-f75ef8952b23"),
                            CategoryId = new Guid("ed419975-8b09-4553-bb59-43b3ed382adb"),
                            Description = "This HP Victus Gaming Laptop 15 includes the Intel Core i5-13420H processor, offering power and efficiency.This laptop also provides vivid details, featuring 75 W TGP for sustained power, NVIDIA DLSS 3 AI Tensor Core, NVIDIA Ada Lovelace Architecture",
                            Price = 77800.00m,
                            Product_Image_Url = "/Images/HP Victus.jpg",
                            Product_Name = "HP Victus Intel Core i5 13th Gen 13420H",
                            qty_in_stock = 20
                        },
                        new
                        {
                            Id = new Guid("7e323a5d-0d1d-49f5-80c4-a2bb4c152f6a"),
                            CategoryId = new Guid("ed419975-8b09-4553-bb59-43b3ed382adb"),
                            Description = "The Vivobook 15, a multipurpose laptop with a 12th-generation Intel U-Series CPU, DDR4 memory, and PCIe 3.0 SSD storage, delivers remarkable performance for daily work.Its three-sided NanoEdge slim-bezel display offers breathtaking images, and its Dirac-designed audio system produces rich, immersive sound.",
                            Price = 50990.00m,
                            Product_Image_Url = "/Images/ASUS-Vivobook-15.png",
                            Product_Name = "ASUS Vivobook 15 ",
                            qty_in_stock = 15
                        },
                        new
                        {
                            Id = new Guid("cba35257-d692-4b76-b033-c2078b0b013b"),
                            CategoryId = new Guid("2a51063a-0d41-4784-97fc-0facbc3675b7"),
                            Description = "Men Collar T-Shirt",
                            Price = 253.00m,
                            Product_Image_Url = "/Images/men-tshirt.jpg",
                            Product_Name = "Men Solid Collar Cotton T-Shirt",
                            qty_in_stock = 8
                        },
                        new
                        {
                            Id = new Guid("51d09fd8-b2f5-4054-a05b-3d16688e89a9"),
                            CategoryId = new Guid("2a51063a-0d41-4784-97fc-0facbc3675b7"),
                            Description = "Round Neck",
                            Price = 274.00m,
                            Product_Image_Url = "/Images/colorblock-roundneck-tshirt.jpg",
                            Product_Name = "Men Colorblock Round Neck Pure Cotton T-Shirt",
                            qty_in_stock = 10
                        },
                        new
                        {
                            Id = new Guid("6408796b-56b0-4c2f-9ade-004c8d7c2624"),
                            CategoryId = new Guid("d026bf3d-5e98-46fd-986e-82c97da687bf"),
                            Description = "Casual Sneaker Outdoor Shoes For Boys And Men",
                            Price = 391.00m,
                            Product_Image_Url = "/Images/casual-sneakers.jpg",
                            Product_Name = "Casual Sneaker",
                            qty_in_stock = 40
                        },
                        new
                        {
                            Id = new Guid("e1147aab-745b-4063-9fb5-99991357a1ad"),
                            CategoryId = new Guid("d026bf3d-5e98-46fd-986e-82c97da687bf"),
                            Description = "WHITE HIGH PREMIUM QUALITY Running Shoes For Men",
                            Price = 478.00m,
                            Product_Image_Url = "/Images/white-sneakers.jpg",
                            Product_Name = "White Shoes",
                            qty_in_stock = 90
                        });
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.HasOne("Entities.Category", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
